site_name: 晦涩弗里曼 | 起源维基
repo_url: https://github.com/obscurefreeman/sourcewiki
repo_name: 为起源维基做出贡献
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  favicon: images/favicon.png
  icon:
    logo: fontawesome/solid/flask
    repo: fontawesome/brands/github
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到浅色模式

nav:
  - 主页:
    - 欢迎来到起源维基: index.md 
    - 撰写和编辑文章: edit.md 
    - 语法: syntax.md 
    - 站外链接: links.md 
  - Gmod:
    - 简介: games/gmod/introduction.md 
    - 添加菜单: games/gmod/spawnmenu.md 
  - 反应下降:
    - 简介: games/alienswarm/introduction.md 
    - 制作挑战: games/alienswarm/creating_a_challenge.md 
    - 制作地图: games/alienswarm/creating_a_map.md 

extra: 
  social:
    # - icon: fontawesome/brands/blog
    #   link: https://obscurefreeman.github.io/blog/
    #   name: 我的博客页面
    - icon: fontawesome/brands/github
      link: https://github.com/obscurefreeman
      name: 我的Github主页
    - icon: fontawesome/brands/discord
      link: https://discord.com/channels/806044973795246080
      name: 我的Discord讨论组
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/id/obscurefreeman/
      name: 我的Steam账号
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/y0juTLeYHfs03dZ
      name: 我的Twitter主页
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCw_S5zgJ6ikGSXtFeAvVK8Q
      name: 我的YouTube频道
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/user/Wonderful-Snow-6080
      name: 我的Reddit主页
    


  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde

# Copyright
copyright: 2023 晦涩弗里曼
