# site_name: 晦涩弗里曼的维基百科
# theme:
#   name: material
#   features:
#     - announce.dismiss
#     - content.action.edit
#     - content.action.view
#     - content.code.annotate
#     - content.code.copy
#     # - content.code.select
#     # - content.tabs.link
#     - content.tooltips
#     # - header.autohide
#     # - navigation.expand
#     - navigation.footer
#     - navigation.indexes
#     # - navigation.instant
#     # - navigation.prune
#     - navigation.sections
#     - navigation.tabs
#     # - navigation.tabs.sticky
#     - navigation.top
#     - navigation.tracking
#     - search.highlight
#     - search.share
#     - search.suggest
#     - toc.follow
#     # - toc.integrate
#   language: zh
#   palette:
#     - scheme: default
#       primary: black
#       accent: indigo
#       toggle:
#         icon: material/brightness-4
#         name: Switch to dark mode
#     - scheme: slate
#       primary: black
#       accent: indigo
#       toggle:
#         icon: material/brightness-7
#         name: Switch to light mode

# # Copyright
# copyright: 2023 晦涩弗里曼

site_name: MkDocs YouTube Tutorial
site_url: https://james-willett.github.io/mkdocs-material-youtube-tutorial/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/james-willett
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">James Willett</a>
