site_name: 晦涩弗里曼 | 起源维基
repo_url: https://github.com/obscurefreeman/sourcewiki
repo_name: 为起源维基做出贡献
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.path
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  favicon: images/favicon.png
  icon:
    logo: fontawesome/solid/flask
    repo: fontawesome/brands/github
    tag:
      default: material/tag
      xml: material/xml
      atom: material/atom
      tools: material/tools
      map: material/map
      controller: material/controller
      flask: fontawesome/solid/flask
      engine: material/engine
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到浅色模式

nav:
  - 主页:
    - 欢迎来到起源维基: index.md 
    - 关于: about.md 
    - 编辑:
      - 规定: rules.md 
      - 撰写和编辑文章: edit.md 
      - 配置: configuration.md 
      - 语法: syntax.md 
      - 站外链接: links.md 
  - Gmod:
    - 简介: games/gmod/introduction.md 
    - 添加菜单: games/gmod/spawnmenu.md 
  - 反应下降:
    - 简介: games/alienswarm/introduction.md 
    - 制作挑战: games/alienswarm/creating_a_challenge.md 
    - 制作地图: games/alienswarm/creating_a_map.md 

extra: 
  social:
    - icon: fontawesome/solid/pen-to-square
      link: https://obscurefreeman.github.io/blog/
      name: 我的博客页面
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/523837807
      name: 我的B站主页
    - icon: fontawesome/brands/github
      link: https://github.com/obscurefreeman
      name: 我的Github主页
    - icon: fontawesome/brands/discord
      link: https://discord.com/channels/806044973795246080
      name: 我的Discord讨论组
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/id/obscurefreeman/
      name: 我的Steam账号
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/y0juTLeYHfs03dZ
      name: 我的Twitter主页
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCw_S5zgJ6ikGSXtFeAvVK8Q
      name: 我的YouTube频道
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/user/Wonderful-Snow-6080
      name: 我的Reddit主页
  tags:
    <tag>: <identifier>
    编程: xml
    Gmod: controller
    反应下降: controller
    地图: map
    维基: flask
    技术: atom
    Lua: language-lua
    起源: engine
  analytics:
    provider: google
    property: G-Y6PB89JDM4
    feedback:
      title: 这个页面有帮助吗？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 这个页面有帮助
          data: 1
          note: >-
            起源维基感谢您的反馈！
        - icon: material/emoticon-sad-outline
          name: 这个页面还需改进
          data: 0
          note: >- 
            感谢您的反馈！
            加入我们的<a href="https://github.com/obscurefreeman/sourcewiki/discussions" target="_blank" rel="noopener">讨论</a>，帮助我们改进此页面。
  consent:
    title: Cookie 同意书
    description: >- 
      本站使用谷歌分析来识别您的重复访问和偏好，并且衡量我们文档是否有效，同时检测用户是否找到了他们正在搜索的内容。在您的同意下，起源维基会变得越来越好。
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - tags:
      tags_file: tags.md
  - search:
      separator: '[\s\u200b\-]'
  # - git-revision-date-localized:
  #     enabled: !ENV [CI, false]
  #     enable_creation_date: true
  #     fallback_to_build_date: true
  #     type: timeago
  # - social
  #     cards_layout_options:
  #       font_family: Noto Sans SC
  - glightbox

# Copyright
copyright: 2023 晦涩弗里曼
